# Usar una imagen base de Node.js
FROM node:lts

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar los archivos package.json y package-lock.json
COPY package*.json ./
# Instalar dependencias de Node.js
RUN npm install

# Instalar Angular CLI globalmente
RUN npm install -g @angular/cli

# Copiar el resto de los archivos de la aplicación
COPY . .

# Exponer el puerto que usará la aplicación Angular
EXPOSE 4200

# Comando para ejecutar la aplicación Angular
CMD ["ng", "serve", "--host", "0.0.0.0"]
